### DISCUSSION TITLE
Can I show the grid export icon when exporting rather than no grid?

### DISCUSSION THREAD

**Discussion by bazcurtis** [slipx06/sunsynk-power-flow-card#214] [General]
I used the no_grid option to grey out the grid when not using it. Can I change the icon to the outgoing grid icon when exporting?

This is my current yaml for the grid and what I am seeing.

```
grid:
  colour: red
  dynamic_colour: true
  show_daily_buy: true
  show_daily_sell: true
  show_nonessential: false
  invert_grid: true
  no_grid_colour: grey
  auto_scale: true
  export_colour: green
  grid_off_colour: grey
```

![Screenshot 2024-01-18 at 10 37 41](https://github.com/slipx06/sunsynk-power-flow-card/assets/7840697/d34f9b90-bd22-4346-9684-0e345102bdb8)

I would like to show this icon

![Screenshot 2024-01-18 at 12 28 00](https://github.com/slipx06/sunsynk-power-flow-card/assets/7840697/9a73f893-86c1-4a40-9435-a27c1f1c7f00)

Ignore the 97, that is the watts

**Comment by slipx06** [comment]
Hi. If you have no grid connection how can you be exporting to the grid? You should check your sensor that you are using for grid_connected_status_194. The grid needs to be connected to show the export icon.

**Comment by bazcurtis** [comment]
I am using my own binary sensor. It works with my card below, but not in the power flow card. Sorry, if I am missing something. In the documentation for Lux 194 is not mentioned. 

```
template:
  - binary_sensor:
      - name: Binary On Grid
        state: "{{ states('sensor.lux_power_from_grid_live') | int(-1) > 0 }}"
        delay_on:
            minutes: 2
      - name: Binary Exporting To Grid
        state: "{{ states('sensor.lux_power_to_grid_live') | int(-1) > 0 }}"
        delay_on:
            minutes: 2
```

```
type: custom:button-card
name: Exporting To The Grid
card_mod:
  style: |
    ha-card {
      height: 100px
    }
entity: binary_sensor.binary_exporting_to_grid
icon: mdi:transmission-tower
size: 100%
state:
  - operator: '=='
    value: 'on'
    color: green
    name: >-
      [[[ return "Exporting To The Grid: " +
      states["sensor.lux_power_to_grid_live"].state; ]]]
    icon: mdi:transmission-tower-export
  - value: 'off'
    color: blue
    icon: mdi:home-outline
    name: Not Exporting
```

**Comment by slipx06** [comment]
The card will display 3 icons for the grid status - Grid connected (importing), Grid Disconnected, Grid connected (exporting). The connection state is based on the grid_connected_status_194.  This is an optional sensor that expects any of the following values (case insensitive):

`on/off,1/0, On-Grid/Off-Grid, On Grid/Off Grid, OnGrid/OffGrid`

In your screenshot is shows the grid as disconnected. If your Lux inverter does not have a sensor for this then you must delete it from you card configuration. If the grid_connected_status_194 entity is deleted it assumes that grid is always connected.  The icon will then change based on the grid power sensor (negative number for export) positive number for import

**Reply by bazcurtis** [reply]
Thanks for the help. This is now working. If it helps others I now have these three views. I removed the 194 line completely below is my yaml

```
type: custom:sunsynk-power-flow-card
cardstyle: full
show_solar: true
inverter:
  model: lux
  modern: false
  auto_scale: true
battery:
  energy: 9600
  shutdown_soc: 10
  show_daily: true
  invert_power: true
  colour: orange
  auto_scale: true
  max_power: 3600
  show_remaining_energy: true
solar:
  colour: green
  show_daily: true
  mppts: 2
  pv1_name: Back
  pv2_name: Front
  auto_scale: true
  dynamic_colour: true
load:
  show_daily: true
  dynamic_colour: true
  dynamic_icon: true
grid:
  colour: red
  dynamic_colour: true
  show_daily_buy: true
  show_daily_sell: true
  show_nonessential: false
  invert_grid: true
  no_grid_colour: grey
  auto_scale: true
  export_colour: green
  grid_off_colour: grey
entities:
  day_pv_energy_108: sensor.lux_solar_output_daily
  inverter_voltage_154: sensor.lux_grid_voltage_live
  load_frequency_192: sensor.lux_grid_frequency_live
  inverter_current_164: none
  inverter_power_175: sensor.lux_battery_flow_live
  inverter_status_59: sensor.lux_status
  day_battery_charge_70: sensor.lux_battery_charge_daily
  day_battery_discharge_71: sensor.lux_battery_discharge_daily
  battery_voltage_183: sensor.lux_battery_voltage_live
  battery_soc_184: sensor.lux_battery
  battery_power_190: sensor.lux_battery_flow_live
  battery_current_191: none
  grid_power_169: sensor.grid_power
  day_grid_import_76: sensor.lux_power_from_grid_daily
  day_grid_export_77: sensor.lux_power_to_grid_daily
  grid_ct_power_172: sensor.lux_grid_flow_live
  day_load_energy_84: sensor.lux_home_consumption_daily
  essential_power: sensor.lux_home_consumption_live
  nonessential_power: none
  aux_power_166: none
  pv_total: sensor.lux_solar_output_live
  pv1_power_186: sensor.lux_solar_output_array_1_live
  pv2_power_187: sensor.lux_solar_output_array_2_live
  pv1_voltage_109: none
  pv1_current_110: none
  pv2_voltage_111: none
  pv2_current_112: none
  inverter_ac_temp: sensor.lux_radiator_1_temperature_live
  inverter_dc_temp: sensor.lux_radiator_2_temperature_live
  remaining_solar: sensor.solcast_forecast_remaining_today
  energy_cost_sell: sensor.agile_current_export_rate
  energy_cost_buy: sensor.agile_current_import_rate
  environment_temp: sensor.met_office_buntingford_temperature_3_hourly
```
![Screenshot 2024-01-22 at 12 18 04](https://github.com/slipx06/sunsynk-power-flow-card/assets/7840697/af39b7a7-1e53-4beb-abcd-d888c7bca534)
![Screenshot 2024-01-22 at 12 31 35](https://github.com/slipx06/sunsynk-power-flow-card/assets/7840697/75e196ae-e8d6-4ced-a716-77fb33124818)
![Screenshot 2024-01-22 at 12 48 59](https://github.com/slipx06/sunsynk-power-flow-card/assets/7840697/652747bb-46d3-4066-a1f5-976271d2ab00)
