### DISCUSSION TITLE
Grid shows disconnected whereas the grid is still on but the current is null.

### DISCUSSION THREAD

**Discussion by adnovea** [slipx06/sunsynk-power-flow-card#233] [General]
My system is configure to have NO injection and sometimes the grid current equals 0.
Despite the "grid_connected_status_194" entity value equals "1", the add-on Grid network switch to red (no grid).
This is a problem because each time I have to physically go and check if the grid is really down.

I would be more accurate to have the NO GRID only depending of the "**grid_connected_status_194**" entity rather than the null current of "_grid_ct_power_172_" entity that is no relevant.
It was probably the case in the past because my problem is quite recent.

**Comment by slipx06** [comment]
There are three attributes you can configure (See below) Are you perhaps not confusing `no_grid_colour` with `grid_off_colour`. Also the grid icon will change and have a line through it when the the grid is disconnected.

`export_colour:` | Optional |   | Sets the colour of all the grid card objects when exporting (selling) energy. Hex codes ('#66ff00' etc) or names (red, green, blue etc). If not set will use the colour: value defined above.
`no_grid_colour:` | Optional |   | Sets the colour of all the grid card objects when there is no grid power. Hex codes ('#66ff00' etc) or names (red, green, blue etc). If not set will use the colour: value defined above total
`grid_off_colour:` | Optional |   | Sets the colour of the grid icon when the grid is disconnected.

**Reply by adnovea** [reply]
Thanks for the explanation.
 I made a confusion between _no_grid_colour_ and _grid_off_colour_.

Nevertheless, I have:
```
grid:
  colour: '#488fc2'
  export_colour: yellow
  no_grid_colour: lightgrey
  grid_off_colour: rgb(192,0,0)
...
entities:
  grid_power_169: sensor.deye_internal_ct_l1_power
  grid_ct_power_172: sensor.deye_external_ct_l1_power
  grid_connected_status_194: sensor.deye_grid_connected_status
```
When **grid_ct_power_172** goes to 0W it turns grey (_no_grid_colour_), 
but when **grid_connected_status_194** goes to 0 there are neither icon nor color changes (_grid_off_colour is ignored_).
If I click the Grid transmission tower icon, the entity shows the correct value 0.

I cannot find my mistake.

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/44359861/087d74f4-c8da-4d2c-98eb-b610fcc2e405)
