### DISCUSSION TITLE
Displaying the backup generator on the card

### DISCUSSION THREAD

**Discussion by maksbit** [slipx06/sunsynk-power-flow-card#269] [Victron]
![Screenshot 2024-02-25 alle 20 52 16](https://github.com/slipx06/sunsynk-power-flow-card/assets/8914341/2420eff4-6e3f-4baf-93d9-4e459f27df4f)
This is my card, I have a 3 phase power system. Victron inverters, which provide for the connection of a backup generator, 3 entities are transmitted from the Cerbo GX system for each phase. How can I display a backup generator on my card?

**Comment by Roving-Ronin** [comment]
@maksbit  That is one of the options that you can use the AUX section of the card (above the house icon) and its aux_ entities for.

**Comment by Roving-Ronin** [comment]
Couldn't you create a template sensor for the inverter with some conditional IF / THEN statements such as IF generator_active_power is >0 then inverter_output is inverter_active_power - generator_active_power.

That would give you a sensor to use for the inverter that shows the full amount of power of the generator is Off, or shows the inverter output (less the generator) of the generator is on. Then just assign that as the inverter on AUX_1 and the generator as aux_2 on the card.

**Reply by maksbit** [reply]
I just added. AUX1 and set the Invert AUX parameter. Added the essence of the total power sensor, and now when running on a generator it simply displays this. But this is not exactly what I would like to see.
![Screenshot 2024-02-26 alle 15 04 35](https://github.com/slipx06/sunsynk-power-flow-card/assets/8914341/dcd7bc1b-1042-4d90-ac85-b52563232959)

**Reply by Roving-Ronin** [reply]
@maksbit Did you create a template sensor? Could you post the yaml (to add yaml tap the ` / ~ key 3 times so you create like this.. but with the 3 of them ):

~~ 
enter your yaml code in between
~~

Also please confirm the name of the sensors for the Victron inverter, the power meter and the sensor measuring the power (active power usually) that senses if the generator is running / producing power.

Could you also please paste the yaml code that you've entered into the sunsynk card, that lists all the battery / grid / aux etc entities your using ?

**Reply by maksbit** [reply]
Since the 3-phase system is assembled from 3 separate inverters, the Victron integration supplies the essence of power from the generator separately for each phase L1, L2, L3. I made this template sensor that sums the power across all three phases.


```
  - platform: template
    sensors:
      load_alternator:
        friendly_name: "load_generator"
        unit_of_measurement: "W"
        device_class: power
        value_template: "{{ states('sensor.victron_system_genset_l1')|float + states('sensor.victron_system_genset_l2')|float + states('sensor.victron_system_genset_l3')|float }}"
```

Here is my sunsynk card:
```
type: custom:sunsynk-power-flow-card
cardstyle: full
show_solar: false
battery:
  energy: 0
  shutdown_soc: 20
  show_daily: false
  auto_scale: true
  invert_power: true
  show_absolute: true
  dynamic_colour: true
  linear_gradient: true
  show_remaining_energy: true
  hide_soc: false
  max_power: 38400
solar:
  show_daily: true
  mppts: 2
load:
  show_daily: false
  auto_scale: true
  dynamic_colour: false
  dynamic_icon: false
  additional_loads: 0
  show_aux: true
  invert_aux: true
  max_power: 45000
  aux_name: Generator
  aux_type: mdi:generator-mobile
  show_absolute_aux: true
  essential_name: Home
  show_daily_aux: false
  aux_load1_name: '123'
  aux_load1_icon: mdi:account
  aux_colour:
    - 43
    - 0
    - 255
  aux_off_colour:
    - 85
    - 255
    - 0
grid:
  show_daily_buy: false
  show_daily_sell: false
  show_nonessential: false
  auto_scale: true
  invert_grid: false
  show_absolute: false
  nonessential_icon: mdi:account
  load1_icon: mdi:account
  load2_icon: ''
  load3_icon: ''
  grid_name: General_IN
  max_power: 45000
  additional_loads: 0
entities:
  inverter_power_175: sensor.total_load_power
  grid_power_169: sensor.total_grid_power
  battery_soc_184: sensor.victron_battery_soc
  battery_power_190: sensor.victron_system_battery_power
  battery_current_191: sensor.victron_battery_current
  battery_temp_182: sensor.victron_battery_temperature
  battery_voltage_183: sensor.victron_battery_voltage
  day_battery_charge_70: sensor.victron_battery_history_dischargedenergy
  day_battery_discharge_71: sensor.victron_battery_history_dischargedenergy
  battery_rated_capacity: sensor.victron_battery_capacity
  inverter_voltage_L2: sensor.victron_vebus_activein_l2_voltage_227
  inverter_voltage_L3: sensor.victron_vebus_activein_l3_voltage_227
  load_frequency_192: sensor.victron_vebus_activein_l2_frequency_227
  inverter_current_L2: sensor.victron_vebus_activein_l2_current_227
  inverter_current_L3: sensor.victron_vebus_activein_l3_current_227
  load_power_L1: sensor.victron_vebus_out_l1_power_227
  load_power_L2: sensor.victron_vebus_out_l2_power_227
  load_power_L3: sensor.victron_vebus_out_l3_power_227
  day_grid_import_76: sensor.victron_vebus_acin1toacout_227
  energy_cost_buy: input_number.energy_price_day
  grid_ct_power_172: sensor.victron_vebus_activein_l1_power_227
  grid_ct_power_L2: sensor.victron_vebus_activein_l2_power_227
  grid_ct_power_L3: sensor.victron_vebus_activein_l3_power_227
  inverter_voltage_154: sensor.victron_vebus_activein_l1_voltage_227
  inverter_current_164: sensor.victron_vebus_activein_l1_current_227
  aux_power_166: sensor.load_alternator
large_font: false
panel_mode: true
show_battery: true
show_grid: true
dynamic_line_width: true
inverter:
  three_phase: true
  auto_scale: true
  modern: false
  model: victron
  autarky: power
max_line_width: 2
decimal_places: 2
```

**Reply by Roving-Ronin** [reply]
@maksbit 
FYI the platform: template  and then - sensor format has been superceded, you'll want to update to the current format.

Also to combine the 3 inverters together, and also add them together if one is offline, and add an availability state to the sensor (this reports 'True' if ANY ONE of the inverters is online, if we used AND instead of OR then the sensor would report FALSE, even if 2 inverters where still running.

Try this sensor to replace the one you provided, this will give you a new 'inverters_active_power' sensor. 

```
template:

  # Provides the combined current Active Power of both inverters, in Watts.
  - sensor:
    - name: "Inverters - Active Power"
      unique_id: inverters_active_power
      unit_of_measurement: "W"
      device_class: "power"
      state_class: measurement
      state: >-
        {% set inverter_l1 = states('sensor.victron_system_genset_l1') | float(default=0) %}
        {% set inverter_l2 = states('sensor.victron_system_genset_l2') | float(default=0) %}
        {% set inverter_l3 = states('sensor.victron_system_genset_l3') | float(default=0) %}

        {% if states('sensor.victron_system_genset_l1') == ['unknown', 'none', 'unavailable'] %}
          {{ inverter_l2 + inverter_l3 }}
        {% else %}
          {% set count = 0 %}
          {% set sum = 0 %}

          {% if states('sensor.victron_system_genset_l1') != ['unknown', 'none', 'unavailable'] %}
            {% set sum = sum + inverter_l1 %}
            {% set count = count + 1 %}
          {% endif %}

          {% if states('sensor.victron_system_genset_l2') != ['unknown', 'none', 'unavailable'] %}
            {% set sum = sum + inverter_l2 %}
            {% set count = count + 1 %}
          {% endif %}

          {% if states('sensor.victron_system_genset_l3') != ['unknown', 'none', 'unavailable'] %}
            {% set sum = sum + inverter_l3 %}
            {% set count = count + 1 %}
          {% endif %}
        
          {% if count > 0 %}
            {{ sum | round(1) }}
          {% else %}
            N/A
          {% endif %}
        {% endif %}
      availability: >-
        {{ states('sensor.victron_system_genset_l1') | is_number
        or states('sensor.victron_system_genset_l2') | is_number 
        or states('sensor.victron_system_genset_l3') | is_number }}
```

Additional Comments / Questions in the YAML below:


```
type: custom:sunsynk-power-flow-card
cardstyle: full                <------  Your missing a bunch of lines from this section. Also items that below here are in other sections.
panel_mode: false
large_font: false
show_solar: false
large_font: false
title: Victron - Power Flows
title_colour: White
title_size: 18px
panel_mode: true
show_battery: true
show_grid: true
dynamic_line_width: true
max_line_width: 2
decimal_places: 2

inverter:                             <------  This section should be up here
  three_phase: true
  auto_scale: true
  modern: false
  model: victron
  autarky: power


battery:
  energy: 0                              <------ What is the size of the battery ? i.e. 20kW = 20,,,
  shutdown_soc: 20
  show_daily: false                   <------ Don't you have any meters to track daily kWh?
  auto_scale: true
  invert_power: true
  show_absolute: true
  dynamic_colour: true
  linear_gradient: true
  show_remaining_energy: true
  hide_soc: false
  max_power: 38400             <------ This is saying you can pull 38.4kW Active Power out of the battery. Is this supposed to be energy: 38400

solar:                                    <------ Do you have any solar panels, or this is a Grid Power + Generator Power only setup ?
  show_daily: true
  mppts: 2

load:
  colour: magenta
  show_daily: false                <------ Don't you have any meters to track daily kWh?
  auto_scale: true
  dynamic_colour: true         <------ Enable this
  dynamic_icon: true            <------ Enable this
  additional_loads: 0
  show_aux: true
  invert_aux: true
  max_power: 45000           <------ Are you actually pulling up to 45kW Active Power ?
  aux_name: Generator
  aux_type: mdi:generator-mobile
  show_absolute_aux: true
  essential_name: Home     <------ LoL more like factory if the kW you listing are correct
  show_daily_aux: false       <------ Don't you have any meters to track daily kWh?
  aux_load1_name: '123'
  aux_load1_icon: mdi:account
  aux_colour: '#2B00FF'    <----- Easier than 3 lines for RGB
  aux_off_colour: lime       <----- Easier than 3 lines for RGB

grid:
  grid_name: Power Grid
  colour: '#FF2400'                         <------ Add
  export_colour: lime                       <------ Add
  no_grid_colour: '#a40013'            <------ Add
  grid_off_colour: '#e7d59f'             <------ Add
  show_daily_buy: false                   <------ Don't you have any meters to track daily kWh?
  show_daily_sell: false                    <------ Don't you have any meters to track daily kWh?
  show_nonessential: false
  auto_scale: true
  invert_grid: false
  show_absolute: false
  nonessential_icon: mdi:account
  load1_icon: mdi:account
  load2_icon: ''
  load3_icon: ''
  max_power: 45000                     <------- 3p 230V is normally 22kV (22000)
  additional_loads: 0

entities:
  inverter_power_175: sensor.total_load_power   <----- This should be the new sensor above ( sensor.inverters_active_power )
  inverter_status_59:                                          <---- Missing, do you have status for each of the 3 inverters ? What are sensor names?
  grid_power_169: sensor.total_grid_power     <---- This should be a sensor you
  grid_voltage:                                                 <---- Missing
  battery_soc_184: sensor.victron_battery_soc
  battery_power_190: sensor.victron_system_battery_power
  battery_current_191: sensor.victron_battery_current
  battery_temp_182: sensor.victron_battery_temperature
  battery_voltage_183: sensor.victron_battery_voltage
  day_battery_charge_70: sensor.victron_battery_history_dischargedenergy   <--- This needs to be the CHARGED energy gone into the battery for the day, not the DISCHARGED you have. 
  day_battery_discharge_71: sensor.victron_battery_history_dischargedenergy  
  battery_rated_capacity: sensor.victron_battery_capacity       <--- This needs to be Ah. Also disables the energy: entry under battery
  inverter_voltage_L2: sensor.victron_vebus_activein_l2_voltage_227
  inverter_voltage_L3: sensor.victron_vebus_activein_l3_voltage_227
  load_frequency_192: sensor.victron_vebus_activein_l2_frequency_227
  inverter_current_L2: sensor.victron_vebus_activein_l2_current_227
  inverter_current_L3: sensor.victron_vebus_activein_l3_current_227
  load_power_L1: sensor.victron_vebus_out_l1_power_227
  load_power_L2: sensor.victron_vebus_out_l2_power_227
  load_power_L3: sensor.victron_vebus_out_l3_power_227
  day_grid_import_76: sensor.victron_vebus_acin1toacout_227   <--- Is this sensor going a reading of kWh imported from the grid today?
  energy_cost_buy: input_number.energy_price_day            <---- Use a price sensor instead of a basic input number
  energy_cost_sell:                                                              <---- Missing and use a price sensor instead of a basic input number
  grid_ct_power_172: sensor.victron_vebus_activein_l1_power_227
  grid_ct_power_L2: sensor.victron_vebus_activein_l2_power_227
  grid_ct_power_L3: sensor.victron_vebus_activein_l3_power_227
  inverter_voltage_154: sensor.victron_vebus_activein_l1_voltage_227    <----- Is this the power meter for the whole site, where it connects to the grid ?
  inverter_current_164: sensor.victron_vebus_activein_l1_current_227
  aux_power_166: sensor.load_alternator
```

Instead of an input number for electricity cost, do you have details of your energy cost tariffs ? Same price 24x7 for buying kWh or different prices at different times and on different days? Do you get paid for kWh to put into grid? How much, same price 24x7 ?

Do you have a power meter that is connected between inverters / house load and where the power grid connection is, so you can get readings of power from / to the grid ?

**Reply by Roving-Ronin** [reply]
@maksbit 

Can you move this thread to the Support --> Victron section please, instead of Category = Q&A ?  
This issue isn't really generator related, but more that there's no guide / template or how to for Victron users.

**Reply by Roving-Ronin** [reply]
@maksbit could you also paste your yaml that your using to query victron modbus? I assume you using something like this in /packages

```
# modbus:
  - name: victron
    type: tcp
    host: 192.168.xx.xx  # use the IP address of your CCGX
    port: 502
    sensors:
      - name: "Grid Power"
        scan_interval: 10
        unit_of_measurement: "W"
        slave: 100
        address: 820
```

**Reply by maksbit** [reply]
> Try this sensor to replace the one you provided, this will give you a new 'inverters_active_power' sensor.

I'll try to change the code, but my template was displaying the total amount correctly.

```
type: custom:sunsynk-power-flow-card
cardstyle: full                <------  Your missing a bunch of lines from this section. Also items that below here are in other sections.
```
>A: I initially used a graphical editor for setup.
```
panel_mode: false
large_font: false
show_solar: false
large_font: false
title: Victron - Power Flows
title_colour: White
title_size: 18px
panel_mode: true
show_battery: true
show_grid: true
dynamic_line_width: true
max_line_width: 2
decimal_places: 2

inverter:                             <------  This section should be up here
  three_phase: true
  auto_scale: true
  modern: false
  model: victron
  autarky: power
```
A: This part of the code is there, but in the end, where to place it is of great importance? This is how the visual editor apparently generated the code.

```
battery:
  energy: 0                              <------ What is the size of the battery ? i.e. 20kW = 20,,,
```
A: I'll correct it, the total battery capacity is 4.8 kW * 8 = 38.4 kW

```
  shutdown_soc: 20
  show_daily: false                   <------ Don't you have any meters to track daily kWh?
 ```
A: There are, but I don’t use them in this configuration yet. This is all displayed in the Energy dashboard HA

```
 auto_scale: true
  invert_power: true
  show_absolute: true
  dynamic_colour: true
  linear_gradient: true
  show_remaining_energy: true
  hide_soc: false
  max_power: 38400             <------ This is saying you can pull 38.4kW Active Power out of the battery. Is this supposed to be energy: 38400
```
A: Thanks, I'll fix it.

```
solar:                                    <------ Do you have any solar panels, or this is a Grid Power + Generator Power only setup ?
  show_daily: true
  mppts: 2
```
A: This system of 3 * Quattro 48/15000/200-2x100 inverters does not have MPPT trackers and I do not have solar panels.

```
load:
  colour: magenta
  show_daily: false                <------ Don't you have any meters to track daily kWh?
```
A: Yes, but I also don’t use it in this card.

```
  auto_scale: true
  dynamic_colour: true         <------ Enable this
  dynamic_icon: true            <------ Enable this
```
A: Thanks, I'll fix it.

```
  additional_loads: 0
  show_aux: true
  invert_aux: true
  max_power: 45000           <------ Are you actually pulling up to 45kW Active Power ?
```
A:  Yes, the total power of my transformer is 55 kW, assembling a power system of 3 inverters 3 * 15 kW = 45 kW

```
  aux_name: Generator
  aux_type: mdi:generator-mobile
  show_absolute_aux: true
  essential_name: Home     <------ LoL more like factory if the kW you listing are correct
```
A: There is nothing strange, all heating is electric. :)

```
  show_daily_aux: false       <------ Don't you have any meters to track daily kWh?
```
A: Yes, but I also don’t use it in this card.

```
  aux_load1_name: '123'
  aux_load1_icon: mdi:account
  aux_colour: '#2B00FF'    <----- Easier than 3 lines for RGB
  aux_off_colour: lime       <----- Easier than 3 lines for RGB
```
A: Ok.

```
grid:
  grid_name: Power Grid
  colour: '#FF2400'                         <------ Add
  export_colour: lime                       <------ Add
  no_grid_colour: '#a40013'            <------ Add
  grid_off_colour: '#e7d59f'             <------ Add
```
A: Ok

```
  show_daily_buy: false                   <------ Don't you have any meters to track daily kWh?
  show_daily_sell: false                    <------ Don't you have any meters to track daily kWh?
```
A: NO.

```  
show_nonessential: false
  auto_scale: true
  invert_grid: false
  show_absolute: false
  nonessential_icon: mdi:account
  load1_icon: mdi:account
  load2_icon: ''
  load3_icon: ''
  max_power: 45000                     <------- 3p 230V is normally 22kV (22000)
  additional_loads: 0
```
A: No, I have a power of 55kW

```
entities:
  inverter_power_175: sensor.total_load_power   <----- This should be the new sensor above ( sensor.inverters_active_power )
```
A: Ok, I'll replace it

```
  inverter_status_59:                                          <---- Missing, do you have status for each of the 3 inverters ? What are sensor names?
```
A: There are many different status sensors, both for each inverter individually and for the entire assembly as a whole, for example **sensor.victron_vebus_activein_activeinput_227** and in normal mode it has the status **AC_INPUT_1**. If any phase disappears, the status will change to **DISCONNECTED**, and then when the generator starts up **AC_INPUT_2**.

```
  grid_power_169: sensor.total_grid_power     <---- This should be a sensor you
```
A: Ok.

```
  grid_voltage:                                                 <---- Missing
```
A: Thanks, I'll fix it.

```
  battery_soc_184: sensor.victron_battery_soc
  battery_power_190: sensor.victron_system_battery_power
  battery_current_191: sensor.victron_battery_current
  battery_temp_182: sensor.victron_battery_temperature
  battery_voltage_183: sensor.victron_battery_voltage
```
```
  day_battery_charge_70: sensor.victron_battery_history_dischargedenergy   <--- This needs to be the CHARGED energy gone into the battery for the day, not the DISCHARGED you have. 
  day_battery_discharge_71: sensor.victron_battery_history_dischargedenergy  
  battery_rated_capacity: sensor.victron_battery_capacity       <--- This needs to be Ah. Also disables the energy: entry under battery
```
A: Ok, I'll try to change the sensors.

```
  inverter_voltage_L2: sensor.victron_vebus_activein_l2_voltage_227
  inverter_voltage_L3: sensor.victron_vebus_activein_l3_voltage_227
  load_frequency_192: sensor.victron_vebus_activein_l2_frequency_227
  inverter_current_L2: sensor.victron_vebus_activein_l2_current_227
  inverter_current_L3: sensor.victron_vebus_activein_l3_current_227
  load_power_L1: sensor.victron_vebus_out_l1_power_227
  load_power_L2: sensor.victron_vebus_out_l2_power_227
  load_power_L3: sensor.victron_vebus_out_l3_power_227
```
```
  day_grid_import_76: sensor.victron_vebus_acin1toacout_227   <--- Is this sensor going a reading of kWh imported from the grid today?
```
A: Yes

```
  energy_cost_buy: input_number.energy_price_day            <---- Use a price sensor instead of a basic input number
```
A: Yes, I have an entity that changes the cost of energy according to a schedule, I have 2 tariff zones.

```
  energy_cost_sell:                                                              <---- Missing and use a price sensor instead of a basic input number
 ```
A: I don't sell energy to the grid.

```
 grid_ct_power_172: sensor.victron_vebus_activein_l1_power_227
  grid_ct_power_L2: sensor.victron_vebus_activein_l2_power_227
  grid_ct_power_L3: sensor.victron_vebus_activein_l3_power_227
```
```
  inverter_voltage_154: sensor.victron_vebus_activein_l1_voltage_227    <----- Is this the power meter for the whole site, where it connects to the grid ?
```
A: No, there is no entity that indicates the total voltage, because in a 3-phase network there must be 3 voltages for each phase. This entity indicates the voltage of phase No. 1
```
  inverter_current_164: sensor.victron_vebus_activein_l1_current_227
  aux_power_166: sensor.load_alternator
```
-------------------------------

>Instead of an input number for electricity cost, do you have details of your energy cost tariffs ? Same price 24x7 for buying kWh or different prices at different times and on different days? Do you get paid for kWh to put into grid? How much, same price 24x7 ?

>Do you have a power meter that is connected between inverters / house load and where the power grid connection is, so you can get readings of power from / to the grid ?

I have 2 tariff zones, there is an entity that changes its value at a strictly set time. In the standard integration of HA "Energia" it works more or less correctly.
--------------------------------

```
# modbus:
  - name: victron
    type: tcp
    host: 192.168.xx.xx  # use the IP address of your CCGX
    port: 502
    sensors:
      - name: "Grid Power"
        scan_interval: 10
        unit_of_measurement: "W"
        slave: 100
        address: 820
```
I am using HACS integration [Victron GX modbusTCP integration](https://github.com/sfstar/hass-victron.git)

**Reply by Roving-Ronin** [reply]
@maksbit 
The inverter total sensor you had is basic in that its just A + B + C = ? 
Give the  'inverters_active_power' sensor I provided a go, it is designed to keep working in the case that one inverter reading fails, in which case it will still calculate the power from the remaining inverter(s), whereas the old sensor will just go 'unknown' or 'unavailable'. Also added an availability check to the sensor itself.

Have you had any success with the updated settings mentioned above, and getting the card working?

PS. How much do you pay per kWh, pit surprised when you mentioned 38.4kW+ and all electrcity for heating as well. Must definitely be less that in Australia per kWh. :-)

**Reply by maksbit** [reply]
>PS. How much do you pay per kWh, pit surprised when you mentioned 38.4kW+ and all electrcity for heating as well. Must definitely be less that in Australia per kWh. :-)

A: The cost of 1 kilowatt during the day is $0.069, at night it is 50% cheaper.

>Have you had any success with the updated settings mentioned above, and getting the card working?

A: Now I’m rewriting the configuration, a little later I’ll post what happened.

**Reply by Roving-Ronin** [reply]
@maksbit  
WOW, in the socialist pit of Australia the politicians have drunk the coolaid and pushed the renewables wheelbarrow, whilst ignoring it doesn't work 24x7 (let alone overcast days, nights, windless times etc) and refusing nuclear and efficient coal (whilst sending it to China etc to use/burn and then be able to kill our industrial sector. >200% increases in the last 18-24months.

We are now paying in the realm of:
Peak - Monday - Friday 7am- 9am and 5pm - 8pm - €0.25343934 p/kWh
Shoulder - Monday - Friday 9am - 5pm and 8pm - 10pm - €0.2293102 p/kWh
Off Peak - Monday - Friday 10pm - 7am and All Weekend - 0.18101892 p/kWh

All depends upon where you live, which DNSP etc, some places people are paying €0.36202705 p/kWh.   Envious at the thoug of your prices :-)

**Comment by maksbit** [comment]
```
template:
  - sensor:
    - name: "Inverters - Active Power"
      unique_id: inverters_active_power
      unit_of_measurement: "W"
      device_class: "power"
      state_class: measurement
      state: >-
        {% set inverter_l1 = states('sensor.victron_system_genset_l1') | float(default=0) %}
        {% set inverter_l2 = states('sensor.victron_system_genset_l2') | float(default=0) %}
        {% set inverter_l3 = states('sensor.victron_system_genset_l3') | float(default=0) %}

        {% if states('sensor.victron_system_genset_l1') == ['unknown', 'none', 'unavailable'] %}
          {{ inverter_l2 + inverter_l3 }}
        {% else %}
          {% set count = 0 %}
          {% set sum = 0 %}

          {% if states('sensor.victron_system_genset_l1') != ['unknown', 'none', 'unavailable'] %}
            {% set sum = sum + inverter_l1 %}
            {% set count = count + 1 %}
          {% endif %}

          {% if states('sensor.victron_system_genset_l2') != ['unknown', 'none', 'unavailable'] %}
            {% set sum = sum + inverter_l2 %}
            {% set count = count + 1 %}
          {% endif %}

          {% if states('sensor.victron_system_genset_l3') != ['unknown', 'none', 'unavailable'] %}
            {% set sum = sum + inverter_l3 %}
            {% set count = count + 1 %}
          {% endif %}
        
          {% if count > 0 %}
            {{ sum | round(1) }}
          {% else %}
            N/A
          {% endif %}
        {% endif %}
      availability: >-
        {{ states('sensor.victron_system_genset_l1') | is_number
        or states('sensor.victron_system_genset_l2') | is_number 
        or states('sensor.victron_system_genset_l3') | is_number }}
```

I can’t understand, when checking the configuration there are no comments, but the entity is not created, the sensor does not appear. I created a separate file with this code: ` /homeassistant/includes/sensors/sensor_active_power_invert.yaml`

**Reply by Roving-Ronin** [reply]
@maksbit 
See: https://www.home-assistant.io/docs/configuration/packages/  

Short version, in the /homeassistant directory create a new directory called 'packages', then edit your configuration.yaml file and add this to it:

```
homeassistant:
  packages: !include_dir_named packages
```

Reload / restart Home Assistant and then place you can make a file say 'victron_derived_sensors.yaml' and place the inverters_active_power code I sent you into it, then save and reload / restart Home Assistant. You should then have that sensor be created / be visible when you look in Settings --> Device & Services --> Entities.

**Reply by maksbit** [reply]
> Short version, in the /homeassistant directory create a new directory called 'packages', then edit your configuration.yaml file and add this to it:

Thank you, I didn’t take into account the fact that everything needs to be done through Packages. The entity has appeared in the system, now I’ll try using this template to remake the sensor for the active energy of the main power input inverters.

**Reply by Roving-Ronin** [reply]
Hi @maksbit ,

Would you please be able to assist with documenting the Victron gear your using, and the integration your using to make the Victron visible in HA? I believe your using Victron GX with this integration: https://github.com/sfstar/hass-victron

Also would you be able to provide the sensors this populates into HA, and the corresponding mapping of these entities to the SunSynk card entities ?

All this is needed to allow documenting setting up Victron with https://github.com/sfstar/hass-victron, so other people can also setup their Victrons.

Victron page needing to be updated: https://slipx06.github.io/sunsynk-power-flow-card/examples/victron.html

**Reply by maksbit** [reply]
> Hi @maksbit ,
> 
> Would you please be able to assist with documenting the Victron gear your using, and the integration your using to make the Victron visible in HA? I believe your using Victron GX with this integration: https://github.com/sfstar/hass-victron
> 
Yes.
> Also would you be able to provide the sensors this populates into HA, and the corresponding mapping of these entities to the SunSynk card entities ?
> 
> All this is needed to allow documenting setting up Victron with https://github.com/sfstar/hass-victron, so other people can also setup their Victrons.
> 
> Victron page needing to be updated: https://slipx06.github.io/sunsynk-power-flow-card/examples/victron.html

I'll try, I've never done this before)

**Reply by Roving-Ronin** [reply]
Thanks. Just write up saying what Victron gear you need to have wired up (given there's so many Victron options and appears you MUST have GX also wired in... shame they charge so much for a basic device). Then just rework the existing example code, assigning all the Victron specific sensors to it... to assist I left the example for SunSynk inverters in there / look at others like the Huawei ones I did (I was a neebie also) ;-)

**Reply by maksbit** [reply]
> Thanks. Just write up saying what Victron gear you need to have wired up (given there's so many Victron options and appears you MUST have GX also wired in... shame they charge so much for a basic device). Then just rework the existing example code, assigning all the Victron specific sensors to it... to assist I left the example for SunSynk inverters in there / look at others like the Huawei ones I did (I was a neebie also) ;-)

I use Cerbo GX +  3 x Quattro 48/15000/200-2x100

**Comment by maksbit** [comment]
Today I have this card config. I can’t figure out where I went wrong that the Remaining Energy of the battery is not displayed. 
```
type: custom:sunsynk-power-flow-card
cardstyle: full
show_solar: false
battery:
  show_daily: false
  auto_scale: true
  invert_power: true
  show_absolute: false
  dynamic_colour: true
  linear_gradient: true
  show_remaining_energy: true
  hide_soc: true
  animate: false
  colour:
    - 34
    - 231
    - 8
  charge_colour:
    - 203
    - 54
    - 16
  shutdown_soc: 10
  energy: 38400
  shutdown_soc_offgrid: 20
solar:
  show_daily: false
  mppts: 2
load:
  show_daily: false
  auto_scale: true
  dynamic_colour: true
  dynamic_icon: true
  additional_loads: 2
  show_aux: true
  invert_aux: true
  max_power: 45000
  aux_name: Generator
  aux_type: mdi:generator-mobile
  show_absolute_aux: true
  essential_name: Home
  show_daily_aux: false
  aux_load1_icon: ''
  aux_colour:
    - 17
    - 255
    - 0
  aux_off_colour:
    - 56
    - 56
    - 56
  aux_loads: 0
  load1_name: Опалення
  load1_icon: mdi:radiator
  load2_icon: mdi:lightbulb-on-60
  load2_name: Світло
  load3_name: Розетки
  load3_icon: mdi:flash-triangle
  aux_dynamic_colour: true
grid:
  show_daily_buy: false
  show_daily_sell: false
  show_nonessential: false
  auto_scale: true
  invert_grid: false
  show_absolute: false
  nonessential_icon: ''
  load1_icon: ''
  load2_icon: ''
  load3_icon: ''
  grid_name: General_IN
  max_power: 45000
  additional_loads: 0
entities:
  battery_soc_184: sensor.victron_system_battery_soc
  battery_power_190: sensor.victron_system_battery_power
  battery_current_191: sensor.victron_battery_current
  battery_temp_182: sensor.victron_battery_temperature
  battery_voltage_183: sensor.victron_battery_voltage
  day_battery_charge_70: sensor.victron_battery_history_dischargedenergy
  day_battery_discharge_71: sensor.victron_battery_history_dischargedenergy
  battery_rated_capacity: sensor.victron_battery_capacity
  inverter_voltage_L2: sensor.victron_vebus_activein_l2_voltage_227
  inverter_voltage_L3: sensor.victron_vebus_activein_l3_voltage_227
  load_frequency_192: sensor.victron_vebus_activein_l2_frequency_227
  inverter_current_L2: sensor.victron_vebus_out_l2_current_227
  inverter_current_L3: sensor.victron_vebus_out_l3_current_227
  load_power_L1: sensor.victron_vebus_out_l1_power_227
  load_power_L2: sensor.victron_vebus_out_l2_power_227
  load_power_L3: sensor.victron_vebus_out_l3_power_227
  day_grid_import_76: sensor.victron_vebus_acin1toacout_227
  energy_cost_buy: input_number.energy_price_day
  grid_ct_power_172: sensor.victron_system_grid_l1
  grid_ct_power_L2: sensor.victron_system_grid_l2
  grid_ct_power_L3: sensor.victron_system_grid_l3
  inverter_voltage_154: sensor.victron_vebus_activein_l1_voltage_227
  inverter_current_164: sensor.victron_vebus_out_l1_current_227
  aux_power_166: sensor.inverters_active_power_generator
  grid_voltage: sensor.victron_vebus_out_l1_voltage_227
  aux_load1: sensor.inverters_active_power_generator
  grid_power_169: sensor.inverters_active_power_grid
  inverter_power_175: sensor.victron_system_system_power
  inverter_status_59: sensor.victron_vebus_state_227
  battery_status: sensor.victron_system_battery_state
  aux_connected_status: sensor.victron_generator_state_100
  essential_load1: sensor.circuit_breaker_qf2_power
  essential_load2: sensor.circuit_breaker_1_1_power
  essential_load3: sensor.circuit_breaker_1_2_power
  battery_soh: sensor.victron_battery_soh
large_font: false
panel_mode: true
show_battery: true
show_grid: true
dynamic_line_width: true
inverter:
  three_phase: true
  auto_scale: true
  modern: false
  model: victron
  autarky: 'no'
max_line_width: 5
decimal_places: 2

```
![image](https://github.com/user-attachments/assets/d77f5393-7017-4c67-ada7-abcf03ad35c6)
