### DISCUSSION TITLE
add multiple batteries

### DISCUSSION THREAD

**Discussion by Splmax** [slipx06/sunsynk-power-flow-card#374] [Ideas]
I am just starting to work with Sunsynk Power Flow card.
Is there a way to manage more than just one battery?
I am currently using 2 battery banks in parallel and will add 2 more.
My suggestion would be identical to the solar options. Here I have the possibility to add 4 devices.

Greetings and thanks!

**Comment by Roving-Ronin** [comment]
@Splmax at the moment, pending if slipx06 releases 'wide' a card able to support multiple inverters / batteries, the option you have is to write a bunch of template sensors that add the various sensors your battery brand provides.

Refer to how this is done for the Huawei batteries: 
https://github.com/slipx06/sunsynk-power-flow-card/blob/main/docs/examples/huawei_packages/huawei_derived_sensors.yaml

Note the batteries, apart from the volts / watts / amps etc also have Status sensors and Temperature sensors that you'll wanto "combine". If you use the Huawei examples, they are written to not just 'add the two values and divide by 2' but instead to 'show worst value' (i.e. for temp it will change to show the value of the highest temp, or for status it will show the one that has an error message/alert etc... given you only also have one place to show these, you'll want to see a status showing something is wrong.

**Comment by JanKraslice** [comment]
Hello very please I am a beginner and your card is perfect and ideal for my needs. 
I just need to add a second battery.

The DEYE 30K (Sunsynk) high voltage inverter, allows you to connect two separate batteries each with its own BMS 1 and BMS 2 
Subsequently, I have two entities from the inverter example and this 
sensor.ss_battery_1_soc
sensor.ss_battery_2_soc

How do I please add a second battery with its own BMS 2 to the card

Thank you

**Comment by slipx06** [comment]
Hi. This has been added to version 6.1.0

**Comment by devastatoralexey** [comment]
It seems that they added support for two batteries, but there are no examples or explanations on how to do this. I added all the sensors. I added the wide:true parameter, I added count:2. But the 2 batteries still did not appear in the map. Can anyone help?
kod:
```
                - type: custom:sunsynk-power-flow-card
                  cardstyle: full
                  wide: true
                  show_solar: true
                  show_grid: true
                  panel_mode: true
                  card_width: '55%'
                  no_card: true
                  large_font: false
                  dynamic_line_width: true
                  card_mod:
                    style: |
                      ha-card {
                        margin-top: -5px !important;
                      }
                      .card {
                        box-shadow: none !important;
                      }
                  inverter:
                    colour: orange
                    autarky: 'no'
                    auto_scale: true
                    modern: true
                    model: 'lux'
                  battery:
                    #count: 2
                    energy: 10400
                    max_power: 5200
                    #shutdown_soc_offgrid: 20
                    shutdown_soc: 20
                    colour: '#9A64A0'
                    show_daily: true
                    invert_power: true
                    show_absolute: true
                    dynamic_colour: true
                    auto_scale: false
                    hide_soc: false
                    show_remaining_energy: true
                    path_threshold: 55
                  solar:
                    show_daily: true
                    mppts: 1
                    max_power: 2760
                    pv1_name: 'Панели кухня'
                    auto_scale: true
                  load:
                    show_daily: true
                    max_power: 5200
                    auto_scale: true
                    essential_name: 'ДОМ'
                  grid:
                    max_power: 5200
                    show_daily_buy: true
                    show_daily_sell: false
                    show_nonessential: false
                    grid_name: 'Город'
                    energy_cost_decimals: 2
                  entities:
                    Priority_load_243: sensor.must_ph18_series_device_mode

                    #inverter_status_59: sensor.powerwall_inverter_charger_status
                    inverter_voltage_154: sensor.must_ph18_series_grid_voltage   # напряжение на инверторе вход с города
                    inverter_current_164: sensor.zmai1_phase_a_current   # амперы на инверторе
                    inverter_power_175: sensor.must_ph18_series_load_power # подключеная нагрузка
                    #aux_power_166: sensor.energomer_energy_power

                    load_frequency_192: sensor.must_ph18_series_ac_output_frequency # частота на инверторе
                    radiator_temp_91: sensor.must_ph18_series_temperature

                    #grid_connected_status_194: binary_sensor.powerwall_inverter_grid_active

                    grid_ct_power_172: sensor.must_ph18_series_grid_power # ваты с города на инвертор
                    grid_power_167: sensor.powerwall_inverter_grid_power
                    grid_voltage: sensor.must_ph18_series_grid_voltage

                     battery_voltage_183: sensor.must_ph18_series_voltage
                     battery2_voltage_183: sensor.must_ph18_series_voltage_2
                    
                     battery_soc_184: sensor.must_ph18_series_state_of_charge
                     battery2_soc_184: sensor.must_ph18_series_state_of_charge_2
                    
                     battery_power_190: sensor.must_ph18_series_power
                     battery2_power_190: sensor.must_ph18_series_power_2
                    
                     battery_current_191: sensor.must_ph18_series_current
                     battery2_current_191: sensor.must_ph18_series_current_2
                    
                     battery_temp_182: sensor.must_ph18_series_temperature_1   #sensor.must_ph18_series_battery_temperature
                     battery2_temp_182: sensor.must_ph18_series_temperature_2_2   #sensor.must_ph18_series_battery_temperature

                    

                    day_battery_charge_70: sensor.daily_batery_charge  #sensor.must_ph18_series_battery_energy_in
                    day_battery_discharge_71: sensor.daily_batery_discharge  #sensor.must_ph18_series_battery_energy_out

                    day_grid_import_76: sensor.daily_grid_buy  #sensor.must_ph18_series_grid_energy_in
                    #day_grid_export_77: sensor.daily_energy_all

                    day_load_energy_84: sensor.daily_home_buy  #sensor.must_ph18_series_load_energy
                    day_pv_energy_108: sensor.daily_pv_energy  #sensor.must_ph18_series_pv_energy

                    pv1_power_186: sensor.pv_power_all
```

**Reply by slipx06** [reply]
Hi. You have commented out count. Remove the hash in front of it i.e 

#count: 2 

You also need to setup your battery2 attributes I.e energy You can use the visual editor

```
battery2
  energy: 5230
```

etc

**Comment by devastatoralexey** [comment]
I redid everything. The second battery does not appear. Maybe someone has at least one working example.

```
                - type: custom:sunsynk-power-flow-card
                  cardstyle: full
                  wide: true
                  show_solar: true
                  show_grid: true
                  panel_mode: true
                  card_width: '55%'
                  no_card: true
                  large_font: false
                  dynamic_line_width: true
                  card_mod:
                    style: |
                      ha-card {
                        margin-top: -5px !important;
                      }
                      .card {
                        box-shadow: none !important;
                      }
                  inverter:
                    colour: orange
                    autarky: 'no'
                    auto_scale: true
                    modern: true
                    model: 'lux'

# Для двух батарей
                  battery:
                    count: 2
                    shutdown_soc: 20
                    colour: '#9A64A0'
                    show_daily: true
                    invert_power: true
                    show_absolute: true
                    dynamic_colour: true
                    auto_scale: false
                    hide_soc: false
                    show_remaining_energy: true
                    path_threshold: 55

                  battery1:
                    energy: 5200
                    max_power: 5200
                    shutdown_soc: 20
                    colour: '#9A64A0'
                    show_daily: true
                    invert_power: true
                    show_absolute: true
                    dynamic_colour: true
                    auto_scale: false
                    hide_soc: false
                    show_remaining_energy: true
                    path_threshold: 55
                  battery2:
                    energy: 5200
                    max_power: 5200
                    shutdown_soc: 20
                    colour: '#9A64A0'
                    show_daily: true
                    invert_power: true
                    show_absolute: true
                    dynamic_colour: true
                    auto_scale: false
                    hide_soc: false
                    show_remaining_energy: true
                    path_threshold: 55

                  solar:
                    show_daily: true
                    mppts: 1
                    max_power: 2760
                    pv1_name: 'Панели кухня'
                    auto_scale: true
                  load:
                    show_daily: true
                    max_power: 5200
                    auto_scale: true
                    essential_name: 'ДОМ'
                  grid:
                    max_power: 5200
                    show_daily_buy: true
                    show_daily_sell: false
                    show_nonessential: false
                    grid_name: 'Город'
                    energy_cost_decimals: 2
                  entities:
                    Priority_load_243: sensor.must_ph18_series_device_mode

                    #inverter_status_59: sensor.powerwall_inverter_charger_status
                    inverter_voltage_154: sensor.must_ph18_series_grid_voltage   # напряжение на инверторе вход с города
                    inverter_current_164: sensor.zmai1_phase_a_current   # амперы на инверторе
                    inverter_power_175: sensor.must_ph18_series_load_power # подключеная нагрузка

                    load_frequency_192: sensor.must_ph18_series_ac_output_frequency # частота на инверторе
                    radiator_temp_91: sensor.must_ph18_series_temperature

                    grid_ct_power_172: sensor.must_ph18_series_grid_power # ваты с города на инвертор
                    grid_power_167: sensor.powerwall_inverter_grid_power
                    grid_voltage: sensor.must_ph18_series_grid_voltage

#две батареи
                    battery_voltage_183: sensor.must_ph18_series_voltage
                    battery2_voltage_183: sensor.must_ph18_series_voltage_2
                    
                    battery_soc_184: sensor.must_ph18_series_state_of_charge
                    battery2_soc_184: sensor.must_ph18_series_state_of_charge_2
                    
                    battery_power_190: sensor.must_ph18_series_power
                    battery2_power_190: sensor.must_ph18_series_power_2
                    
                    battery_current_191: sensor.must_ph18_series_current
                    battery2_current_191: sensor.must_ph18_series_current_2
                    
                    battery_temp_182: sensor.must_ph18_series_temperature_1   #sensor.must_ph18_series_battery_temperature
                    battery2_temp_182: sensor.must_ph18_series_temperature_2_2   #sensor.must_ph18_series_battery_temperature

                    day_battery_charge_70: sensor.daily_batery_charge  #sensor.must_ph18_series_battery_energy_in
                    day_battery_discharge_71: sensor.daily_batery_discharge  #sensor.must_ph18_series_battery_energy_out

                    day_grid_import_76: sensor.daily_grid_buy  #sensor.must_ph18_series_grid_energy_in
                    #day_grid_export_77: sensor.daily_energy_all

                    day_load_energy_84: sensor.daily_home_buy  #sensor.must_ph18_series_load_energy
                    day_pv_energy_108: sensor.daily_pv_energy  #sensor.must_ph18_series_pv_energy

                    pv1_power_186: sensor.pv_power_all
```
