### DISCUSSION TITLE
problems with network icon and aux load

### DISCUSSION THREAD

**Discussion by R0DRIG0MEL0** [slipx06/sunsynk-power-flow-card#473] [General]
I have problems with the network icon and the blue color that appears on my aux, can you help me?
![Captura de tela 2024-06-03 151751](https://github.com/slipx06/sunsynk-power-flow-card/assets/60002358/e079a350-a6e8-47ca-9aa8-a0302b507607)

**Comment by slipx06** [comment]
Sure. What do you need help with. The grid icon requires the `grid_connected_status_194:` sensor to be defined. 

`grid_connected_status_194: | Optional | binary_sensor.sunsynk_grid_connected_status | Grid connected status (case insensitive) on/off,1/0, On-Grid/Off-Grid, or On Grid/Off Grid`

**Comment by R0DRIG0MEL0** [comment]
the sensor is already defined, but the status does not respond successfully, I have always been informed of the disconnection icon


![Captura de tela 2024-06-04 083001](https://github.com/slipx06/sunsynk-power-flow-card/assets/60002358/cff95c79-9e0d-4c40-a8a9-23480f7a04ec)

**Comment by slipx06** [comment]
It wont work because it is expecting one of the following `on/off,1/0, On-Grid/Off-Grid, or On Grid/Off Grid`. Your sensor looks to be providing a state of connected/disconnected? I can update but please confirm the state values.

**Comment by R0DRIG0MEL0** [comment]
this is the translation of my language on the interface, the native sensor is on/off

![Captura de tela 2024-06-04 084316](https://github.com/slipx06/sunsynk-power-flow-card/assets/60002358/85541904-1923-4e6e-8f5d-00f0ef02892d)

**Comment by R0DRIG0MEL0** [comment]
I remember that in the past it was working perfectly, but after some updates the sensor stopped working

**Comment by slipx06** [comment]
That sensor should work fine. Can you share your config. Also have you tried creating another template sensor or using another random sensor that reports on/off to test.

If you remove this sensor `grid_connected_status_194:` it should also show the normal connected transmission icon.

**Reply by R0DRIG0MEL0** [reply]
I tried this alternative, but the icon remains the same

Nothing I do solves the icon

![Captura de tela 2024-06-04 170433](https://github.com/slipx06/sunsynk-power-flow-card/assets/60002358/0606dfd2-711e-4661-9aab-75eb94388ae8)

**Reply by slipx06** [reply]
Create a new card with the default or absolute minimum (see below) config. Start adding back your sensors until you find the one that is causing a problem

```
type: custom:sunsynk-power-flow-card
cardstyle: full
show_solar: true
solar:
  mppts: 2
entities:
  inverter_power_175: sensor.sunsynk_inverter_power
  grid_power_169: sensor.sunsynk_grid_power
  grid_ct_power_172: sensor.sunsynk_grid_ct_power
  pv1_power_186: sensor.sunsynk_pv1_power
```
