### DISCUSSION TITLE
I do not consume electricity from the network, but it shows that there is consumption

### DISCUSSION THREAD

**Discussion by amgstone** [slipx06/sunsynk-power-flow-card#548] [EASun Power]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I do not consume electricity from the network, but it shows that there is consumption
![IMG_20241027_095340](https://github.com/user-attachments/assets/5bf912e3-2414-49cb-bc68-6b0f222aabfa)

### Expected behaviour

I do not consume electricity from the network, but it shows that there is consumption

### Card Version

new

### Home Assistant Version

new

**Comment by slipx06** [comment]
Hi.
According to your sensor readings you are consuming more power than you are producing. 
721W of Solar power, but consuming 755W (414W +341W) from battery and load. Are your sensors accurate? Are you providing your own sensor for essential_power?

**Comment by amgstone** [comment]
type: custom:sunsynk-power-flow-card
cardstyle: compact
show_solar: true
card_height: 300px
show_grid: true
inverter:
  modern: true
  colour: grey
  autarky: power
  model: solaredge
solar:
  mppts: 2
  show_daily: true
  max_power: 8600
  pv1_max_power: 4300
  pv2_max_power: 4300
  display_mode: 2
  efficiency: 1
battery:
  energy: 15000
  colour: pink
  shutdown_soc: 10
  show_daily: true
  max_power: 5500
  invert_power: true
  full_capacity: 99
  empty_capacity: 0
  show_absolute: true
  show_remaining_energy: true
  hide_soc: true
load:
  show_daily: true
  colour: "#5fb6ad"
  animation_speed: 6
  max_power: 7200
  additional_loads: 4
  load1_name: Car
  load1_icon: mdi:ev-station
  load2_name: Boiler
  load2_icon: mdi:water-boiler
  load3_name: Farm
  load3_icon: mdi:server-network
  load4_name: Vent
  load4_icon: mdi:hvac
  dynamic_colour: true
grid:
  grid_name: Мережа
  off_threshold: 0
  show_daily_buy: true
  additional_loads: 0
  show_nonessential: false
  nonessential_icon: mdi:ev-station
  max_power: 9000
  auto_scale: true
  show_daily_sell: false
entities:
  inverter_voltage_154: none
  load_frequency_192: none
  inverter_current_164: none
  inverter_power_175: none
  grid_power_169: sensor.smg_output_power
  battery_soc_184: sensor.jk_bms_state_of_charge
  battery_power_190: sensor.jk_bms_power
  grid_ct_power_172: sensor.smg_mains_power
  grid_connected_status_194: binary_sensor.energy_in_sensor
  no_grid_colour: green
  inverter_status_59: sensor.smg_ii_operation_mode
  pv1_power_186: sensor.smg_ii_pv_average_power
  pv2_power_187: sensor.smg_ii_2_pv_average_power
  pv1_voltage_109: none
  pv1_current_110: none
  pv2_voltage_111: none
  pv2_current_112: none
  day_pv_energy_108: sensor.soniachni_paneli
  day_battery_charge_70: sensor.bms0_charging_energy_today
  day_battery_discharge_71: sensor.bms0_discharging_energy_today
  day_load_energy_84: sensor.solar_plus_energy_minus_battery_sensor
  day_grid_import_76: sensor.spozhito_elektroenergiyi_za_sogodni
  essential_load1: sensor.oncharger_power
  essential_load2: sensor.ten_boiler_power
  essential_load3: sensor.fermi_power
  essential_load4: sensor.recuperator_power
  remaining_solar: sensor.prognoz_na_sogodni
large_font: false

**Comment by slipx06** [comment]
You should provide an `essential_power:` sensor that measure your house load

**Comment by amgstone** [comment]
in entities: add essential_power: sensor.smg_output_power
![IMG_20241029_081526](https://github.com/user-attachments/assets/a686a401-56b5-47c0-a126-03e72bc91a88)

it is not always such a difference, sometimes the values ​​are evened out

**Comment by slipx06** [comment]
What inverter are you using and which integration into HA?

**Comment by amgstone** [comment]
easun smg-ll

**Comment by MBRetrofit** [comment]
This is my Easun SMG II correct integration, all works beautiful,

```
type: custom:sunsynk-power-flow-card
cardstyle: full
show_solar: true
battery:
  shutdown_soc: 22
  show_daily: true
  shutdown_soc_offgrid: 20
  soc_end_of_charge: 95
  remaining_energy_to_shutdown: true
  invert_power: false
  animate: true
  show_remaining_energy: true
  invert_flow: true
  auto_scale: true
  max_power: 17
  count: 1
  show_absolute: true
  linear_gradient: true
  energy: 17
  dynamic_colour: true
  colour:
    - 68
    - 74
    - 162
  charge_colour:
    - 76
    - 211
    - 39
solar:
  show_daily: true
  mppts: 1
  animation_speed: 1
  max_power: 6
  pv1_max_power: 6
  colour:
    - 251
    - 231
    - 9
  pv1_name: South
  dynamic_colour: false
load:
  show_daily: true
  colour:
    - 225
    - 78
    - 14
  off_colour:
    - 211
    - 13
    - 53
  max_colour:
    - 20
    - 173
    - 51
  auto_scale: true
grid:
  show_daily_buy: false
  show_daily_sell: false
  show_nonessential: false
  max_power: 6000
  auto_scale: true
  invert_grid: false
  colour:
    - 99
    - 79
    - 24
entities:
  load_frequency_192: sensor.bridge_smg_output_frequency
  inverter_current_164: sensor.bridge_smg_output_effective_current
  inverter_power_175: sensor.bridge_smg_average_inverter_power
  inverter_status_59: sensor.bridge_smg_operation_mode
  grid_ct_power_172: sensor.bridge_smg_average_mains_power
  nonessential_power: none
  day_pv_energy_108: sensor.bridge_smg_pv_energy_today
  pv1_power_186: sensor.bridge_smg_pv_average_power
  pv1_voltage_109: sensor.bridge_smg_pv_average_voltage
  pv1_current_110: sensor.bridge_smg_pv_charging_average_current
  total_pv_generation: sensor.energy_production_tomorrow
  battery_power_190: sensor.bridge_smg_battery_average_power
  battery_current_191: sensor.bridge_smg_battery_average_current
  battery_voltage_183: sensor.bridge_smg_battery_average_voltage
  battery_soc_184: sensor.bridge_smg_battery_state_of_charge
  inverter_voltage_154: sensor.bridge_smg_effective_inverter_voltage
  grid_voltage: sensor.bridge_effective_inverter_voltage
  grid_power_169: sensor.bridge_smg_average_mains_power
  day_load_energy_84: sensor.bridge_smg_output_energy_today
  day_battery_discharge_71: sensor.daily_discharge
  day_battery_charge_70: daily_charge
  battery_temp_182: sensor.bridge_bms_mosfet_temperature
  battery_rated_capacity: sensor.bridge_bms_full_capacity
  battery_soh: sensor.bridge_bms_state_of_health
  battery_status: sensor.bridge_bms_status
  essential_power: sensor.bridge_smg_output_active_power
inverter:
  modern: true
  autarky: "no"
  auto_scale: true
  model: easun
  colour:
    - 31
    - 178
    - 219
show_battery: true
show_grid: true
dynamic_line_width: true
wide: false
large_font: true
title: Power Flow Card
title_colour:
  - 227
  - 224
  - 222
```
