### DISCUSSION TITLE
Grid voltages and frequency not being displayed

### DISCUSSION THREAD

**Discussion by peteDDD** [slipx06/sunsynk-power-flow-card#617] [Q&A]
Please see the screen capture and the code below.   I do not understand grid voltages (which comes from a helper for averaging the voltages of phases A and B (L1/L2)) is not being shown on the power-flow-card.  Note that the voltage and frequency data is being displayed on the output side of the inverter but not on the grid side and, from the cards below the power-flow-card, we can see that the data is available.  

ALSO, whenever I try to edit the card settings in the show editor window, all changes revert after being saved... so some of the configurations that the UI does not offer, such as the individual phase voltages, cannot be added by editing the yaml in the show editor window...very strange...

![image](https://github.com/user-attachments/assets/5858132c-c14c-43e8-8776-97bc791cc15e)

```
type: custom:sunsynk-power-flow-card
cardstyle: lite
decimal_places_energy: 1
decimal_places: 2
dynamic_line_width: true
large_font: true
show_grid: true
show_solar: true
show_battery: true
inverter:
  three_phase: true
  autarky: energy
battery:
  energy: 16384
  shutdown_soc: 20
  show_daily: true
  count: 1
  max_power: 8000
  shutdown_soc_offgrid: 5
  soc_end_of_charge: 100
  remaining_energy_to_shutdown: true
  show_remaining_energy: true
  invert_flow: true
solar:
  show_daily: true
  mppts: 2
  pv1_name: PV1
  pv2_name: PV2
load:
  show_daily: true
  load1_icon: ""
grid:
  show_daily_buy: true
  show_daily_sell: false
  show_nonessential: false
  grid_name: Naturgy
  disconnected_icon: mdi:power-plug-off-outline
entities:
  inverter_voltage_154: sensor.bms_inv_inverter_voltage_a
  inverter_current_164: sensor.bms_inv_inverter_load_current_a
  inverter_power_175: srne_current_load_Power_a
  inverter_voltage_L2: sensor.bms_inv_inverter_voltage_b
  inverter_current_L2: sensor.bms_inv_inverter_load_current_B
  inverter_status_59: sensor.bms_inv_charge_state
  dc_transformer_temp_90: sensor.bms_inv_dc_to_dc_temperature
  radiator_temp_91: sensor.bms_inv_dc_to_ac_temperature
  load_frequency_192: sensor.bms_inv_inverter_frequency
  load_power_L1: sensor.bms_inv_current_load_power_a
  load_power_L2: sensor.bms_inv_current_load_power_b  
  day_battery_charge_70: sensor.bms_inv_battery_charge_today
  day_battery_discharge_71: sensor.bms_inv_battery_discharge_today
  battery_voltage_183: sensor.bms_inv_battery_voltage
  battery_soc_184: sensor.bms_inv_battery_soc
  battery_power_190: sensor.bms_inv_bms1_power
  battery_current_191: sensor.bms_inv_bms1_current
  battery_rated_capacity: sensor.bms_inv_bms1_actual_battery_capacity
  battery_soh: sensor.bms_inv_bms1_state_of_health
  grid_power_169: sensor.sunsynk_grid_power
  day_grid_import_76: sensor.bms_inv_line_power_consumption_of_the_day
  grid_ct_power_172: sensor.bms_inv_grid_a_power
  grid_ct_power_L2: sensor.bms_inv_grid_b_power
  grid_voltage: sensor.average_grid_voltage_phase_a_b
  grid_connected_status_194: binary_sensor.inverter_grid_connected_status  
  day_load_energy_84: sensor.bms_inv_load_power_consumption_of_the_day
  essential_power: none
  nonessential_power: none
  day_pv_energy_108: sensor.sunsynk_day_pv_energy
  pv1_power_186: sensor.sunsynk_pv1_power
  pv2_power_187: sensor.sunsynk_pv2_power
  pv1_voltage_109: sensor.sunsynk_pv1_voltage
  pv1_current_110: sensor.sunsynk_pv1_current
  pv2_voltage_111: sensor.sunsynk_pv2_voltage
  pv2_current_112: sensor.sunsynk_pv2_current

```
