### ISSUE TITLE
Autoscale and units

### ISSUE THREAD

**Issue by wgumaa** [slipx06/sunsynk-power-flow-card#168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With the latest version, when autoscale is turned on units disappear. I was able to recreate this with all formats; compact, lite and full. 

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/105917603/5506d552-f6fe-4639-b98d-61aae31d383b)

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/105917603/976613b4-8460-49f0-ae3b-d4ef335e5b1f)

When I turn off Autoscale the units appear. 

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/105917603/e9f5f968-1a2b-46ac-b2b0-9ab7931726b3)

### Steps To Reproduce

Turn on or off autoscale. 

### Expected behaviour

Units should not not be affected. 

### Card Version

4.4.1

### Home Assistant Version

Core 2023.12.0

**Comment by slipx06** [comment]
It means that those sensors do not have the `unit_of_measurement` attribute configured so the card does not know how to scale them. Turning `auto_scale` off the card just assumes that it is kWh.  If you are using template sensors make sure you have added it.

```
- sensor:
      - name: "SS Daily PV 108"
        state: >
          {{state_attr('sensor.sunsynk_input', 'etoday')|float(0)|round(1)}}
        unit_of_measurement: kWh
```

You can confirm in developer tools

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/0e96d69a-51eb-42c6-9742-b536e370b8f2)
