### ISSUE TITLE
Auto convert W to kWh

### ISSUE THREAD

**Issue by shingsam** [slipx06/sunsynk-power-flow-card#20]
Thank's for creating this beautiful power flow. Very useful for me who use old inverters.
Can u add auto convert W to kWh for calculating total daily?
Cause my entity use W, soo to long number on card.
Ex my value: 12.345 kWh why not 12.3 kWh.

Thanks.

**Comment by slipx06** [comment]
Hi. Not sure I understand you correctly but if you are receiving wH and want to convert to kWh this is best handled outside of the card using a template sensor. e.g.

```
sensor:
  - platform: template
    sensors:
      wH_to_kWh:
	friendly_name: "Daily Energy kWh"
        value_template: "{{ (states('sensor.daily_Wh') | float /1000) | round(2) }}"
        unit_of_measurement: 'kWh' 
```
