### ISSUE TITLE
GoodWe Shutdown SOC - example code - legacy

### ISSUE THREAD

**Issue by mamo-nick** [slipx06/sunsynk-power-flow-card#201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://slipx06.github.io/sunsynk-power-flow-card/examples/goodwe.html
There is a legacy template code of example "GoodWe Shutdown SOC" 
```
- platform: template
    sensors:
      goodwe_shutdown_soc:
        friendly_name: "GoodWe Shutdown SOC"
        unit_of_measurement: "%"
        icon_template: mdi:battery-arrow-down
        value_template: "{{100 - states('number.depth_of_discharge_on_grid') | int }}"
```

### Expected behaviour

I recommend to use current code for template:
```
- sensor:
    - name: GoodWe Shutdown SOC
      unique_id: goodwe_shutdown_soc
      unit_of_measurement: "%"
      icon: mdi:battery-arrow-down
      state: "{{100 - states('number.depth_of_discharge_on_grid') | int }}"
```

### Card Version

current

### Home Assistant Version

2023.11.0
