### ISSUE TITLE
Not showing 3rd additional non-essential load

### ISSUE THREAD

**Issue by duanemck** [slipx06/sunsynk-power-flow-card#208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When configuring `grid.additional_loads` to `3`, only the first 2 loads are displayed. I have configured a name and icons for the 3rd load and I have set `use_timer_248` to `false`.

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/429394/110cdbc0-1800-4d16-9ff6-53ea62b29cc9)

### Steps To Reproduce

1. In `grid` config:
```
              additional_loads: 3
              load1_name: Geyser
              load2_name: Pool
              load3_name: Oven
              load1_icon: boiler
              load2_icon: pump
              load3_icon: oven
```
2. In `entities` config:
```
entities:
              use_timer_248: false
              priority_load_243: false
              ...
              non_essential_load1: sensor.geyser_real_time_usage
              non_essential_load2: sensor.pool_real_time_usage
              non_essential_load3: sensor.oven_real_time_usage
```

### Expected behaviour

See all 3 additional loads (geyser/pool/oven)

### Card Version

4.9.1

### Home Assistant Version

2024.1.1

### Configuration

```shell
Relevant snippets under "Steps to Reproduce"
```
