### ISSUE TITLE
Deye 8 KW Solar Assistant Configuration

### ISSUE THREAD

**Issue by StevenSterzik** [slipx06/sunsynk-power-flow-card#33]
Hi there,

Great card, its beautiful! I attempted to configure it against my setup Deye 8 KW through Solar Assistant and the config was greatly different. Don't think I have everything configured correctly but thought others could benefit from the effort. I have listed at the bottom the configurations I was not able to figure out from my config.

```yaml
type: custom:sunsynk-power-flow-card
cardstyle: full
show_solar: 'yes'
battery:
  energy: 9600
  shutdown_soc: 15
  show_daily: 'yes'
solar:
  show_daily: 'yes'
  mppts: one
load:
  show_daily: 'yes'
grid:
  show_daily_buy: 'yes'
  show_daily_sell: 'no'
  show_nonessential: 'yes'
entities:
  use_timer_248: switch.use_timer
  priority_load_243: switch.prioritize_load
  inverter_grid_voltage_154: sensor.grid_voltage
  inverter_load_freq_192: sensor.ac_output_frequency
  inverter_out_164: sensor.inverter_output_current
  inverter_out_175: sensor.load_power
  grid_status_194: switch.grid_charge_point_1
  inverter_status_59: sensor.overall_state
  batchargeday_70: sensor.battery_energy_in
  batdischargeday_71: sensor.battery_energy_out
  battery_voltage_183: sensor.battery_voltage
  battery_soc_184: sensor.battery_state_of_charge
  battery_out_190: sensor.battery_power
  battery_current_191: sensor.battery_current
  inverter_load_grid_169: sensor.grid_power
  grid_buy_day_76: sensor.grid_energy_in
  grid_sell_day_77: sensor.grid_energy_out
  grid_external_power_172: sensor.grid_power_ct
  loadday_84: sensor.load_energy
  essential_power: sensor.load_power_essential
  nonessential_power: sensor.load_power_non_essential
  aux_power_166: sensor.aux_output_power
  solarday_108: sensor.pv_energy
  pv1_power_186: sensor.pv_power_1
  pv2_power_187: sensor.pv_power_2
  pv1_v_109: sensor.pv_voltage_1
  pv1_i_110: sensor.pv_current_1
  pv2_v_111: sensor.pv_voltage_2
  pv2_i_112: sensor.pv_current_2
```

Config I was not able to figure out were 

```yaml
inverter_out_164
inverter_status_59
aux_power_166
grid_status_194
```
