### ISSUE TITLE
Option: When charging battery from grid, subtract this power from shown house load

### ISSUE THREAD

**Issue by jasonmadigan** [slipx06/sunsynk-power-flow-card#336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently when charging from the grid, the house load power is shown as 7300W. 

Power coming from the grid in the example below is 6300W, meaning the house load is about 1000W.

<img width="515" alt="Screenshot 2024-03-25 at 20 40 42" src="https://github.com/slipx06/sunsynk-power-flow-card/assets/4467/b6707f58-0968-4cf9-9675-7fbcac6829c8">

### Expected behaviour

I would expect the house load (7300) to instead show as 1000W. I'm unsure if this is a bug, but it would be a nice option to show the house load distinctly when a battery is charging via the grid.

### Mode

lite

### Context / Reason

n/a

**Comment by slipx06** [comment]
Hi. What sensor are you using for `essential_power:` which is your house load?

**Comment by jasonmadigan** [comment]
Thanks for getting back to me. Probably something I've configured wrong then perhaps.

`essential_power: none`

Full config is:

```yaml
type: custom:sunsynk-power-flow-card
cardstyle: compact
show_solar: true
battery:
  energy: 0
  invert_power: true
  show_daily: true
  shutdown_soc: 10
  auto_scale: false
  show_absolute: true
  show_remaining_energy: false
  linear_gradient: true
solar:
  show_daily: true
  mppts: 1
  auto_scale: false
  dynamic_colour: false
load:
  show_daily: true
grid:
  show_daily_buy: true
  show_daily_sell: true
  show_nonessential: true
entities:
  use_timer_248: switch.deye_sunsynk_sol_ark_use_timer
  priority_load_243: select.deye_sunsynk_sol_ark_energy_pattern
  inverter_voltage_154: sensor.deye_sunsynk_sol_ark_ac_output_voltage
  load_frequency_192: sensor.deye_sunsynk_sol_ark_ac_output_frequency
  inverter_current_164: sensor.sunsynk_inverter_current
  inverter_power_175: sensor.deye_sunsynk_sol_ark_load_power
  grid_connected_status_194: binary_sensor.sunsynk_grid_connected_status
  inverter_status_59: sensor.sunsynk_overall_state
  day_battery_charge_70: sensor.deye_sunsynk_sol_ark_daily_battery_energy_in
  day_battery_discharge_71: sensor.deye_sunsynk_sol_ark_daily_battery_out
  battery_voltage_183: sensor.deye_sunsynk_sol_ark_battery_voltage
  battery_soc_184: sensor.deye_sunsynk_sol_ark_battery_state_of_charge
  battery_power_190: sensor.deye_sunsynk_sol_ark_battery_power
  battery_current_191: sensor.deye_sunsynk_sol_ark_battery_current
  grid_power_169: sensor.deye_sunsynk_sol_ark_grid_power
  day_grid_import_76: sensor.deye_sunsynk_sol_ark_daily_grid_energy_in
  day_grid_export_77: sensor.deye_sunsynk_sol_ark_daily_grid_energy_out
  grid_ct_power_172: sensor.deye_sunsynk_sol_ark_grid_power
  day_load_energy_84: sensor.deye_sunsynk_sol_ark_daily_load_energy
  essential_power: none
  nonessential_power: none
  aux_power_166: sensor.sunsynk_aux_power
  day_pv_energy_108: sensor.deye_sunsynk_sol_ark_daily_pv_energy
  pv1_power_186: sensor.deye_sunsynk_sol_ark_pv_power_1
  pv2_power_187: sensor.deye_sunsynk_sol_ark_pv_power_2
  pv1_voltage_109: sensor.deye_sunsynk_sol_ark_pv_voltage_1
  pv1_current_110: sensor.deye_sunsynk_sol_ark_pv_current_1
  pv2_voltage_111: sensor.deye_sunsynk_sol_ark_pv_voltage_2
  pv2_current_112: sensor.deye_sunsynk_sol_ark_pv_current_2
  battery_status: sensor.deye_battery_status
large_font: true
panel_mode: true
show_battery: true
inverter:
  modern: false
  model: deye
  autarky: 'no'
  colour:
    - 118
    - 227
    - 249
show_grid: true
dynamic_line_width: true
```

Unsure if related (might be), but during grid charging of the batteries at night, things get a bit wonky:

![IMG_3615](https://github.com/slipx06/sunsynk-power-flow-card/assets/4467/1074b6b4-8982-4ee4-ac06-474608fc9143)

Grid power at this time should be ~+6200W, with about 5kW headed to the battery (and about 1200W house load). My sensor data are from Solar Assistant via MQTT, so I may have misconfigured some (or have some which switch positive/negative where the card doesn't expect them to...).
