### ISSUE TITLE
Grid power sensor

### ISSUE THREAD

**Issue by zlakes01** [slipx06/sunsynk-power-flow-card#40]
Hi. I have Solax inverter with two grid sensors one for import and one for export. Is it posible to use those two sensors for grid_external_power_172  entity?

**Comment by slipx06** [comment]
Hi
You should create a template sensor that combines these two values. Assuming both sensors report a positive number for grid import and grid export you can use the template below as the card expects a negative value for grid export. Replace the sensor names. If your grid export sensor is already negative then just swap those two sensors around in the formula below

```
- platform: template
  sensors:
    grid_power:
      unit_of_measurement: "W"
      value_template: "{{ states('sensor.grid_import')|float - states('sensor.grid_export')|float }}"
```
