### ISSUE TITLE
Unable to access sensors from options in the setup of the card 

### ISSUE THREAD

**Issue by devilliersjohnny** [slipx06/sunsynk-power-flow-card#433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to access sensors from options in the setup of the card 

![sensor_error](https://github.com/slipx06/sunsynk-power-flow-card/assets/22364421/a4d6acf9-3b47-4222-abe4-eb56941059f2)

Where as the documentation says that I should?

![sensor_error_documentation](https://github.com/slipx06/sunsynk-power-flow-card/assets/22364421/c8b05ddb-ee6b-4b4f-aa84-e92b4a3c7252)

 The same holds true for all the other text_input fields that I have tested so far

### Steps To Reproduce

1. Create the sensor same as below 

```yaml
- name: "EDB I1 Battery Shutdown SOC"
    unique_id: edb_i1_battery_shutdown_soc
    unit_of_measurement: "%"
    icon: mdi:battery-outline
    device_class: battery
    state: >
      {% if states('input_text.edb_i1_battery_shutdown_soc_input_text') | is_number %}
        {% set battery_soc = states('input_text.edb_i1_battery_shutdown_soc_input_text')  | float | round(0) %}
      {% else %}
        {% set battery_soc = 'None' %}
      {% endif %}
      {{ battery_soc }}
```

2. Create `Input_text` feild for `edb_i1_battery_shutdown_soc_input_text`  
3. Reload Yaml
4. Set value for `input_text.edb_i1_battery_shutdown_soc_input_text`
5. Input `sensor.edb_i1_battery_shutdown_soc` into `Battery Options` under `Shutdown SOC`  and note that the card does not accept the value ( the input is underlined in red... see above )

### Expected behaviour

According to the documentation and dashboard example ( see https://github.com/slipx06/Sunsynk-Home-Assistant-Dash/blob/main/Dashboard.yaml) )  provided I would like to see the data from the sensors be pulled through to the cards configuration 

### Card Version

v4.37.0

### Home Assistant Version

2024.5.3
