### ISSUE TITLE
Load Box color switched for Load2 and Load3

### ISSUE THREAD

**Issue by Scoperius** [slipx06/sunsynk-power-flow-card#467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Box color for Load2 is based on Load3 value and for Load3 is based on Load2 value 

### Steps To Reproduce

Last version available for today. Used is Lite card version

### Expected behaviour

Load2 box color based on Load2 value
Load3 box color based on Load3 value

### Card Version

Last

### Home Assistant Version

Last

**Comment by slipx06** [comment]
@Scoperius I cant reproduce this. Everything looks good on my end. Please share your config or more info

  ```
essential_load1: sensor.sunsynk_pv1_power
  essential_load2: sensor.sunsynk_pv2_power
  essential_load3: input_number.test_number
  essential_load4: sensor.sunsynk_pv3_power
```

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/7227275/7eda3cc0-9806-498a-a6e4-2e2b829929ca)

**Comment by Scoperius** [comment]
Hi, I have only 3 loads. see the configuration:
```
load:
  show_daily: true
  additional_loads: 3
  load1_name: IVT AirX-130
  load1_icon: mdi:heat-pump-outline
  load2_name: 'Bazén '
  load2_icon: mdi:pool
  auto_scale: true
  dynamic_colour: true
  dynamic_icon: true
  load3_name: Výřivka
  load3_icon: mdi:pool-thermometer
```
![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/86469550/12b4e908-151f-4c3d-b719-cda4790456dc)

```
  essential_load2: sensor.pl06_plug_tu_power
  essential_load2_extra: sensor.filtrace_spotreba
  essential_load3: sensor.vyrivka_denni_spotreba
```
