### ISSUE TITLE
Load3 always rounded for 2 places

### ISSUE THREAD

**Issue by Scoperius** [slipx06/sunsynk-power-flow-card#468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Load3 value rounded to 2 decimal places regardless entity is defined to be rounded for 1 decimal place and there is no possibility how to change. 

### Expected behaviour

Either to use the rounding as defined for the entity or add the possibility to change per user requirement. 

### Card Version

Last

### Home Assistant Version

Last

**Comment by slipx06** [comment]
Is this essential or nonessential load? What sensor are you using? Whats the unit of measurement. Do you have auto scale enabled?

**Comment by Scoperius** [comment]
Hi, I have only 3 loads. see the configuration:
```
load:
  show_daily: true
  additional_loads: 3
  load1_name: IVT AirX-130
  load1_icon: mdi:heat-pump-outline
  load2_name: 'Bazén '
  load2_icon: mdi:pool
  auto_scale: true
  dynamic_colour: true
  dynamic_icon: true
  load3_name: Výřivka
  load3_icon: mdi:pool-thermometer
```
```
  essential_load3: sensor.vyrivka_denni_spotreba
```

It is Daily consuption in kWh for whirlpool

![image](https://github.com/slipx06/sunsynk-power-flow-card/assets/86469550/6871926b-f054-4033-81ce-807a21282111)
