### ISSUE TITLE
Have separate sensors for battery charge/discharge

### ISSUE THREAD

**Issue by pameruoso** [slipx06/sunsynk-power-flow-card#517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I understand that the card shows the power battery discharge and charge direction and power based on the sign of the value passed by the sensor (must provide one sensor)

### Expected behaviour

 With growatt  you have 2 separate sensors both positive. if battery is discharging the specific sensor is positive and shows how much power the battery is giving to the load. If the battery is charging the discharging sensors is 0 and the charging one is higher than 0.

### Possible Solutions

 Is it possible to have 2 separate sensors that show the battery power usage and hence the power direction from the battery?

### Mode

Both

### Context / Reason

adding capability for growatt inverter

**Comment by slipx06** [comment]
Hi. Quick fix is to just create a template sensor. 

```
template:
  - sensor:
      - name: "Battery Power"
        unique_id: battery_power
        device_class: "power"
        unit_of_measurement: "W" 
        icon: mdi:battery
        state_class: measurement
        state: >
          {% set charge = states('sensor.battery_charge') | float %}
          {% set discharge = states('sensor.battery_discharge') | float %}
          {{ (discharge - charge) |float(0)|round(0) }}
```
