### ISSUE TITLE
Support of davidrapan/ha-solarman integration

### ISSUE THREAD

**Issue by vvv2542** [slipx06/sunsynk-power-flow-card#695]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

The following entities of [davidrapan/ha-solarman](https://github.com/davidrapan/ha-solarman) integration have values ​​that the card does not support:
``` yaml
entities:
  ...
  use_timer_248: select.inverter_time_of_use
  priority_load_243: select.inverter_energy_pattern
  prog1_charge: select.inverter_program_1_charging
  prog2_charge: select.inverter_program_2_charging
  prog3_charge: select.inverter_program_3_charging
  prog4_charge: select.inverter_program_4_charging
  prog5_charge: select.inverter_program_5_charging
  prog6_charge: select.inverter_program_6_charging
  ...
```
As a result, the timer and priority are not shown:

![Image](https://github.com/user-attachments/assets/06549217-86d0-4a06-a03a-8fb37577f01c)

### Expected behaviour

![Image](https://github.com/user-attachments/assets/2fc8cd27-40b8-419b-8b34-355183c0db4a)

### Possible Solutions

Add support for required entity values.

use_timer_248:
- Enabled
- Disabled
- Monday
- ...
- Sunday
- Weekdays
- Weekend
- Week
- Week -Monday
- ...
- Week -Sunday

priority_load_243:
- Battery First
- Load First

progN_charge:
- Disabled
- Grid
- Generator
- Both

### Mode

Both

### Context / Reason

I propose a pull request.
