### ISSUE TITLE
PV efficiency not displayed

### ISSUE THREAD

**Issue by Loic691** [slipx06/sunsynk-power-flow-card#701]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Hi all
Thanks for this great integration.
I have a Deye micro inverter with 2 PV each on 1 MPPT.
The PV power, voltage and current are clearly displayed.
I have configured PV Max to 1000, PV1 max to 500 et PV2 max to 500.
But there is no diaplayed value. See capture

Thanks 

![Image](https://github.com/user-attachments/assets/f119c361-e420-4ab8-bb5f-1a42087fbcd0)

### Expected behaviour

Efficency displayed

### Card Version

v6.8.0

### Home Assistant Version

2025.6.1

### Configuration

```
type: custom:sunsynk-power-flow-card
cardstyle: lite
show_solar: true
battery:
  energy: 0
  shutdown_soc: 20
  show_daily: true
solar:
  show_daily: true
  mppts: 2
  pv1_name: Chalet E
  dynamic_colour: true
  pv2_name: Chalet W
  auto_scale: true
  animation_speed: 10
  invert_flow: false
  efficiency: 1
  off_threshold: 0
  display_mode: 2
  max_power: 1000
  pv1_max_power: 500
  pv2_max_power: 500
load:
  show_daily: true
  dynamic_colour: true
  invert_load: false
  dynamic_icon: true
  load2_name: Info
  load1_name: Piscine
  show_aux: false
  auto_scale: true
  load1_icon: mdi:pool
  load2_icon: mdi:check-network-outline
  load3_icon: mdi:hvac
  load3_name: CVC
  load4_name: Electro M.
  load4_icon: mdi:fridge
  load5_name: Cumulus
  load6_name: Autres
  load5_icon: mdi:water-boiler
  additional_loads: 6
  label_daily_load: MAISON (JOUR)
  load6_icon: mdi:lightning-bolt
  animation_speed: 6
  max_power: 9000
grid:
  show_daily_buy: true
  show_daily_sell: false
  show_nonessential: true
  show_absolute: false
  auto_scale: true
  invert_grid: false
  load1_name: oiuououio
  invert_flow: false
  grid_name: ENEDIS
  label_daily_grid_buy: CONSOMATION (JOUR)
entities:
  day_grid_import_76: sensor.compteur_total_journalier
  pv1_power_186: sensor.sun_m100g4_eu_q0_pv1_power
  pv1_voltage_109: sensor.sun_m100g4_eu_q0_pv1_voltage
  pv2_voltage_111: sensor.sun_m100g4_eu_q0_pv2_voltage
  pv2_current_112: sensor.sun_m100g4_eu_q0_pv2_current
  essential_load2: sensor.groupe_domotique_puissance
  essential_load1: sensor.groupe_piscine_puissance
  grid_voltage: sensor.rt2_tension_mesuree
  pv2_power_187: sensor.sun_m100g4_eu_q0_pv2_power
  day_pv_energy_108: sensor.sun_m100g4_eu_q0_today_production
  pv1_current_110: sensor.sun_m100g4_eu_q0_pv1_current
  inverter_status_59: sensor.sun_m100g4_eu_q0_device_state
  inverter_voltage_154: sensor.sun_m100g4_eu_q0_grid_voltage
  load_frequency_192: sensor.sun_m100g4_eu_q0_grid_frequency
  inverter_current_164: sensor.sun_m100g4_eu_q0_grid_current
  dc_transformer_temp_90: sensor.sun_m100g4_eu_q0_temperature
  environment_temp: sensor.temperature_sht35
  essential_load3: sensor.groupe_chauffage_puissance
  essential_load4: sensor.groupe_electromenager_puissance
  essential_load5: sensor.groupe_eau_chaude_puissance
  essential_load6: sensor.groupe_autres_puissance
  day_load_energy_84: sensor.total_load_energy_daily
  essential_load1_extra: sensor.piscine_ondilo_temperature
  remaining_solar: sensor.prod_solaire_restante_jour
  pv_total: sensor.sun_m100g4_eu_q0_pv_power
  grid_ct_power_172: sensor.rt2_t1_puissance_generale
  total_pv_generation: sensor.sun_m100g4_eu_q0_total_production
  grid_power_169: sensor.rt2_t1_puissance_generale
  inverter_power_175: sensor.sun_m100g4_eu_q0_power
show_battery: false
show_grid: true
inverter:
  three_phase: false
  auto_scale: true
  modern: true
  model: deye
  autarky: energy
large_font: true
wide: false
dynamic_line_width: false
grid_options:
  columns: 48
  rows: auto

```

### Relevant log output

```shell

```
